services:
  hanko-migrate:
    build: ../../backend
    volumes:
      - type: bind
        source: ./config.yaml
        target: /etc/config/config.yaml
    command: --config /etc/config/config.yaml migrate up
    restart: on-failure
    depends_on:
      postgresd:
        condition: service_healthy
    networks:
      - intranet
  hanko:
    depends_on:
      hanko-migrate:
        condition: service_completed_successfully
    build: ../../backend
    ports:
      - '8000:8000' # public
      - '8001:8001' # private
    restart: unless-stopped
    command: serve --config /etc/config/config.yaml all
    volumes:
      - type: bind
        source: ./config.yaml
        target: /etc/config/config.yaml
    networks:
      - intranet
    environment:
      - PASSWORD_ENABLED
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend_https.rule=Host(`backend.test.de`)"
      - "traefik.http.routers.backend_https.tls=true"
      - "traefik.http.routers.backend_https.entrypoints=websecure"
  postgresd:
    image: postgres:12-alpine
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=hanko
      - POSTGRES_PASSWORD=hanko
      - POSTGRES_DB=hanko
    healthcheck:
      test: pg_isready -U hanko -d hanko
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - intranet
  hankojs:
    build: ../../hanko-js
    ports:
      - "9500:80"
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.js_https.rule=Host(`js.test.de`)"
      - "traefik.http.routers.js_https.tls=true"
      - "traefik.http.routers.js_https.entrypoints=websecure"
  example:
    build: ../../example
    ports:
      - "8888:8080"
    environment:
      - HANKO_URL=https://backend.test.de:11111
      - HANKO_URL_INTERNAL=http://hanko:8000
      - HANKO_ELEMENT_URL=https://js.test.de:11111/element.hanko-auth.js
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.example_https.rule=Host(`example.test.de`)"
      - "traefik.http.routers.example_https.tls=true"
      - "traefik.http.routers.example_https.entrypoints=websecure"
  mailslurper:
    image: marcopas/docker-mailslurper:latest
    ports:
      - '8080:8080' # web UI
      - '8085:8085'
    networks:
      - intranet
  traefik:
    image: "traefik:v2.6"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:11111"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
    ports:
      - "11111:11111"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../../../../certs:/tools/certs"
      - "./traefik:/etc/traefik/dynamic_conf:ro"
    networks:
      - intranet
networks:
  intranet:
